wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.11.7
    start_time: 1709094225.774286
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.7
      5: 0.13.10
      6: 4.38.1
      8:
      - 1
      - 4
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.001
n_classes:
  desc: null
  value: 10
subset:
  desc: null
  value: 10
wandb_name:
  desc: null
  value: null
wandb_project:
  desc: null
  value: day3-resnet
